title:        Luqi Pan
tagline:      "Luqi Pan"
author:
  name:       "Luqi Pan"
  email:      "luqi.pan@gmail.com"
markdown:     rdiscount
permalink:    /:categories/:year-:month-:day-:title
pygments:     true
paginate:     5
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]

