# Setup
title:        Luqi Pan
tagline:      "Luqi Pan"
author:
  name:       "Luqi Pan"
  email:      "luqi.pan@gmail.com"
  github:     https://github.com/LuqiPan
description:      Not anything, not yet.</p><p class="lead" style="color:white">Worry for the bear! </p><p class="lead" style="color:white">Keep calm and carry on.
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]

# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Pagination
paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/poole/hyde
