# Setup
title:        Luqi Pan
tagline:      "Love to learn new stuff"
author:
  name:       "Luqi Pan"
  email:      "luqi.pan@gmail.com"
  github:     https://github.com/LuqiPan
description:      Not anything, not yet. </p></li><li class="lead" >Worry for the bear! </p></li><li class="lead" >Keep calm and carry on.</p>
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md", "insert-modified.rb"]

# Dependencies
markdown:         kramdown
highlighter:      pygments
kramdown:
  input: GFM

# Permalinks
permalink:        /:year/:month/:title

# Pagination
paginate:         10

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
