title:        Luqi Pan
tagline:      "It's Luqi"
# url:          http://andhyde.com
author:
  name:       "Luqi Pan"
  email:      "luqi.pan@gmail.com"
markdown:     rdiscount
permalink:    /:catagories/:year-:month-:day-:title
pygments:     true
paginate:     5
